# Site settings
title: Linux Kafası
description: Linux haberlerini takip edebileceğin bir haber platformu
url: https://linuxkafasi.org

lang: tr
timezone: Europe/Istanbul

github_username: linuxkafasi
instagram_username: linuxkafasi
twitter_username: linuxkafasi
google_analytics: UA-115651505-2
disqus:
  shortname: linuxkafasi

# Jekyll SEO tag
## DOC: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
twitter:
  username: linuxkafasi
  card: summary_large_image

logo: favicon.ico

social:
  name: Linux Kafası
  links:
  - https://github.com/linuxkafasi
  - https://instagram.com/linuxkafasi
  - https://twitter.com/linuxkafasi

webmaster_verifications:
  google: DiLWDO560uylzKdOt5xK0HARv98LeswYPGWsTQBZEPE
  yandex: 6b403db6b2861102
  bing: F0753531671625A58667A9EF265A32CB

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-gist
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

# Build settings
markdown: kramdown
theme: minima
sass:
  style: compressed
permalink: /:year/:month/:slug
defaults:
  -
    values:
      layout: post
