# Site settings
title: Linux Kafası
description: Yazılım hakkında haber alırken loop da bırkmayan kaynak
url: https://linuxkafasi.org

lang: tr
timezone: Europe/Istanbul

github_username:    linuxkafasi
instagram_username: linuxkafasi
twitter_username:   linuxkafas
google_analytics:   UA-115651505-2

# Jekyll SEO tag
## DOC: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
twitter:
  username: linuxkafas
  card: summary

logo: favicon.ico

social:
  name: Linux Kafası
  links:
  - https://github.com/linuxkafasi
  - https://instagram.com/linuxkafasi
  - https://twitter.com/linuxkafas

webmaster_verifications:
  google: DiLWDO560uylzKdOt5xK0HARv98LeswYPGWsTQBZEPE
  yandex: 7464b07d7e6747e7

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
  style: compressed
permalink: /:year/:month/:slug
defaults:
  -
    values:
      layout: post
