# Site settings
title: Linux Kafası
description: Yazılım hakkında haber alırken loop da bırkmayan kaynak
url: https://linuxkafasi.org

lang: tr
timezone: Europe/Istanbul

github_username:  linuxkafasi
google_analytics: UA-115651505-2
disqus:
  shortname: linuxkafasi

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
  style: compressed
permalink: /:year/:month/:slug
defaults:
  -
    values:
      layout: post
