# Site settings
title: Linux Kafası
description: Herşeyi ile katkı yapabileceğin bir blog sayfası
baseurl:
url: https://linuxkafasi.org

lang: tr
timezone: Europe/Istanbul

google_analytics: UA-115651505-2
disqus:
  shortname: linuxkafasi

# Social links
github_username: linuxkafasi
rss: RSS

# Build settings
markdown: CommonMark
theme: minima
sass:
  sass_dir: _sass
  style: compressed
defaults:
  -
    values:
      layout: post

# Exclude files and directories
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
